[versions]
java = "21"

gson = "2.11.0"
api-paper = "1.21.3-R0.1-SNAPSHOT"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
api-paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "api-paper" }